# Thông tin k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate ddl-auto: Dùng 'validate' ?? ki?m tra xem Entity Java có kh?p v?i b?ng MySQL không
spring.jpa.hibernate.ddl-auto=validate

# In câu l?nh SQL ra console ?? d? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true