# Thông tin k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
# Khóa bí m?t (B?n có th? ??i thành m?t chu?i c?c dài và khó ?oán)
app.jwt.secret=ChungTaDangXayDungHeThongBaoMatJWTChoDoAnKienTruc4LopCuaToi
# Th?i gian s?ng c?a Token: Tính b?ng mili-giây (Ví d?: 86400000 = 24 ti?ng)
app.jwt.expirationMs=86400000
# Hibernate ddl-auto: Dùng 'validate' ?? ki?m tra xem Entity Java có kh?p v?i b?ng MySQL không
spring.jpa.hibernate.ddl-auto=update

# In câu l?nh SQL ra console ?? d? debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
